# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: 2.1

executors:
  daml-docker-executor:
    docker:
      - image: cimg/openjdk:11.0

commands:
  setup_nix:
    description: Set up Nix
    steps:
      - run:
          name: Generate nix cache key
          command: |
            set -euo pipefail

            git log -n1 --format=%H nix shell.nix daml.yaml > /tmp/nix-cache-key
            sudo mkdir /nix
            sudo chown circleci /nix
            echo 'export USER=circleci' >> "$BASH_ENV"
      - restore_cache:
          keys:
          - nix-{{ checksum "/tmp/nix-cache-key" }}
      - run:
          name: Setup Nix
          command: |
            set -euo pipefail

            if [ -f ~/.config/nix/nix.conf ]; then
                echo '. /home/circleci/.nix-profile/etc/profile.d/nix.sh' >> "$BASH_ENV"
                exit 0
            fi

            # Disabling sandbox because:
            # 1. It doesn't work on CircleCI (sethostname is not allowed)
            # 2. We don't plan to build anything, so the risk is fairly low
            mkdir -p ~/.config/nix
            echo 'sandbox = false' >> ~/.config/nix/nix.conf

            sh <(curl -fsSL --retry 8 https://releases.nixos.org/nix/nix-2.13.3/install) --no-daemon
            . /home/circleci/.nix-profile/etc/profile.d/nix.sh
            nix-shell shell.nix --run 'echo "Done loading all packages."'
            echo '. /home/circleci/.nix-profile/etc/profile.d/nix.sh' >> "$BASH_ENV"
      - save_cache:
          key: nix-{{ checksum "/tmp/nix-cache-key" }}
          paths:
          - /nix
          - /home/circleci/.nix-profile
          - /home/circleci/.nix-channels
          - /home/circleci/.nix-defexpr
          - /home/circleci/.config/nix
  install_yq:
    description: "Install yq from binary"
    steps:
      - run:
          name: Install yq
          command: |
            mkdir -p $HOME/yq
            curl -L https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -o $HOME/yq/yq &&\
              chmod +x $HOME/yq/yq &&\
              echo 'export PATH=$HOME/yq/yq:$PATH' >> $BASH_ENV
  install_gh:
    description: "Install GitHub Cli"
    steps:
      - run:
          name: Install gh
          command: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
  set_sdk_version:
    description: "Set Daml SDK version environment version"
    steps:
      - run:
          name: Set Daml SDK version
          command: echo 'export SDK_VERSION=$(yq e '.sdk-version' daml.yaml)' >> $BASH_ENV
  import_gpg_key:
    description: "Setup GPG for signing artifacts as part of a release"
    steps:
      - run:
          name: Import Digital Asset GPG key
          command: echo ${gpg_code_signing} | base64 -d | gpg --import --quiet
  run_release:
    description: "Run Release"
    steps:
      - run:
          name: "Get target release version"
          command: echo 'export VERSION=$(yq e '.version' daml.yaml)' >> $BASH_ENV
      - run:
          name: "Validate target release version"
          command: |
            if [[ `git tag | grep -Fx "v$VERSION" - | wc -l` -eq 0 ]] ; then
              echo "New tag detected ${VERSION}. Releasing..."
            else
              echo "Tag ${VERSION} already exists; Skipping Release."
              circleci-agent step halt
            fi
      - run:
          name: "Sign dar"
          command: gpg --armor --detach-sign .daml/dist/daml-ctl-${VERSION}.dar
      - run:
          name: "Tag and push to GitHub"
          command: |
            if [[ `awk 'BEGIN { FS="."} { print $NF-1 }' \<<< ${VERSION}` -le 2 ]] ; then
              gh release create v${VERSION} .daml/dist/daml-ctl-${VERSION}.dar* --generate-notes
            else
              gh release create v${VERSION} .daml/dist/daml-ctl-${VERSION}.dar* --generate-notes --prerelease
            fi
      - store_artifacts:
          path: .daml/dist/daml-ctl-${VERSION}.dar
          destination: daml-ctl-dar-${VERSION}

jobs:
  build:
    executor: daml-docker-executor
    steps:
      - checkout
      - install_yq
      - set_sdk_version
      - install_sdk
      - run:
          name: Daml build
          command: daml build
      - run:
          name: Daml test
          command: daml test
      - save_cache:
          paths:
            - .daml
          key: daml-ctl-{{ .Revision }}
  release:
    executor: daml-docker-executor
    steps:
      - checkout
      - install_yq
      - install_gh
      - restore_cache:
          keys:
            - daml-ctl-{{ .Revision }}
      - import_gpg_key
      - run_release

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
  build_and_release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - release:
          context:
            - github-fin-eng-context
            - npn-publish
          requires:
            - build
          filters:
            branches:
              only:
                - master
